# Site settings
title: Hack Swjtu
description: "Fuck Swjtu Everything" 
baseurl: "" # the subpath of your site
url: "https://hackswjtu.github.io/"

# User settings
username: HackSwjtu 
user_title: Hack Swjtu
email: gua@desgard.com
twitter_username: 
github_username: HackSwjtu
gplus_username:  
disqus_username: hack-swjtu

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: post
    url: /posts
  - title: about us
    url: /about
# projects in header index
projects:
  - name: Postime
    url: https://github.com/HackSwjtu/Postime
    introduce: ä¸€æ¬¾å¸¦æœ‰è†œæ€§çš„ chrome æ’ä»¶ã€‚æ”¯æŒæ•™åŠ¡ç½‘ã€ç½‘ç»œä¸­å¿ƒã€å›¾ä¹¦é¦†ç­‰å…éªŒè¯ç å¡«å†™ï¼Œæ”¯æŒä¸€é”®è¯„ä»·è¯¾ç¨‹ç­‰åŠŸèƒ½ã€‚æ¯èŠ‚çœçš„ä¸€ç§’ï¼Œè®©æˆ‘ä»¬ç»­èµ·æ¥ï¼ğŸ˜„
  - name: Clawjtu 
    url: https://github.com/HackSwjtu/weapp-clawjtu 
    introduce: ã€å¼€å‘ä¸­ã€‘ç”¨äºäº¤å¤§è®²åº§åŠç«èµ›ä¿¡æ¯æŸ¥è¯¢çš„å¾®ä¿¡å°ç¨‹åºã€‚ä¸ºè·å–æ›´å‰æ²¿çš„ç§‘æŠ€çŸ¥è¯†è€Œé€ ï¼Œè®©æˆ‘ä»¬çœ¼ç•Œæ›´åŠ å¼€é˜”ã€‚
  - name: äº¤å¤§ç‘å£«åˆ€ 
    url: http://wangzhe.cloud/swjtu
    introduce: æˆå‘˜ WangZhe å¤§ç¥è£èª‰å‡ºå“ã€‚ç”¨äºè®¡ç®—ä¸ªäººä¿ç ”å¹³å‡åˆ†ã€ä¿ç ”æ’åã€é€‰è¯¾è€å¸ˆæŒ‚ç§‘ç‡ä¿¡æ¯ã€è¯¾ç¨‹æ€»å¹³å‡åˆ†ç­‰å®ç”¨æ•°æ®ã€‚è®©ä½ æ›´åŠ äº†è§£è‡ªèº«æˆç»©ï¼Œè¿›è€Œå¼¥è¡¥è‡ªå·±çš„ä¸è¶³ã€‚ 
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules', 'README.md']
